# Top-level configuration
name = "mastra-agents"
main = "src/cloudflare/index.ts" # Adjust path if your entry point is elsewhere
compatibility_date = "2024-04-03" # Use a recent date

# Durable Object Binding
[[durable_objects.bindings]]
name = "AGENTS_DO" # Binding name accessible in the Worker code (env.AGENTS_DO)
class_name = "AgentDO" # The exported class name from your Worker code

# Durable Object Migrations (Required for deploying new DO classes)
[[migrations]]
tag = "v1" # Used to identify the migration step
new_classes = ["AgentDO"] # List of new DO classes being introduced

# Vectorize Binding
[[vectorize]]
binding = "VECTORIZE_INDEX" # Binding name accessible in the Worker code (env.VECTORIZE_INDEX)
index_name = "your-vectorize-index-name" # IMPORTANT: Replace with your actual Vectorize index name

# Note: Secrets must be set using `wrangler secret put <KEY>`
# Required secrets:
# OPENROUTER_API_KEY
# SHARED_AUTH_SECRET
# CLOUDFLARE_ACCOUNT_ID
# CLOUDFLARE_API_TOKEN
# UPSTASH_URL
# UPSTASH_TOKEN

# Add [vars] here if you have non-secret configuration values
# [vars]
# MY_VARIABLE = "my-value"